#!/bin/sh

uci set luci.main.mediaurlbase='/luci-static/argon'
uci commit luci


ln -sf /sbin/ip /usr/bin/ip

sed -i "s/# //g" /etc/opkg/distfeeds.conf

[ -f '/bin/bash' ] && sed -i 's|root:x:0:0:root:/root:/bin/ash|root:x:0:0:root:/root:/bin/bash|g' /etc/passwd

#echo "59.111.239.62 httpdns.n.netease.com" >> /etc/hosts && cat /etc/hosts | sort | uniq > /tmp/tmp_hosts && cat /tmp/tmp_hosts > /etc/hosts
echo "10 2 * * * cd /usr/share/unblockneteasemusic/core/ && openssl req -new -x509 -key server.key -out server.crt -days 3650  -subj "/CN=*.music.163.com" && cd" >> /etc/crontabs/root && cat /etc/crontabs/root | sort | uniq > /tmp/tmp_cron_root && cat /tmp/tmp_cron_root > /etc/crontabs/root

echo "/etc/openclash/" >> /etc/sysupgrade.conf && cat /etc/sysupgrade.conf | sort | uniq > /tmp/tmp_sysupgrade_conf && cat /tmp/tmp_sysupgrade_conf > /etc/sysupgrade.conf
sed -i '/option disabled/d' /etc/config/wireless
sed -i '/set wireless.radio${devidx}.disabled/d' /lib/wifi/mac80211.sh
wifi up

uci set dhcp.@dnsmasq[0].cachesize='1500'
uci set dhcp.@dnsmasq[0].min_ttl='3600'
uci set dhcp.@dnsmasq[0].filter_aaaa='0'
uci set dhcp.@dnsmasq[0].localservice='0'
uci set dhcp.@dnsmasq[0].nonwildcard='0'
uci del dhcp.@dnsmasq[0].rebind_protection
uci set dhcp.@dnsmasq[0].rebind_protection='0'
uci set dhcp.lan.ra='hybrid'
uci set dhcp.lan.ndp=''
uci set dhcp.lan.dhcpv6=''
uci set dhcp.lan.ignore='0'
uci set dhcp.lan.ra_management='1'
uci set dhcp.lan.ra_default='1'
uci set dhcp.lan.force='1'
uci commit dhcp

uci set network.@globals[0].ula_prefix=''
uci set network.globals.packet_steering='1'
uci set network.lan.delegate='0'
uci set network.wan.mtu=1460
uci set network.wan.metric='41'
uci set network.wan.delegate='0'
uci set network.wan.ipv6='auto'
uci commit network
uci set turboacc.config.sfe_flow='0'
uci set turboacc.config.hw_flow='0'
uci set turboacc.config.sw_flow='0'
uci set turboacc.config.fullcone_nat='1'
uci commit turboacc
uci set fstab.@global[0].anon_mount=1
uci commit fstab
uci set upnpd.upnpd.enabled='0'
uci set upnpd.upnpd.igdv1='1'
uci set upnpd.config.igdv1='1'
uci set upnpd.config.enabled='0'
uci del upnpd.config.enable_upnp
uci del upnpd.config.enable_natpmp
uci set upnpd.config.external_iface='wan'
uci commit upnpd

uci set uhttpd.main.rfc1918_filter=0
uci set uhttpd.main.redirect_https=0
uci set uhttpd.main.http_keepalive=0
uci commit uhttpd
/etc/init.d/uhttpd restart

uci set firewall.@defaults[0].fullcone='1'
uci set firewall.@defaults[0].flow_offloading='1'
uci commit firewall

#dnsmasq 
sed -i '/log-facility/d' /etc/dnsmasq.conf
echo "log-facility=/dev/null" >> /etc/dnsmasq.conf

uci set system.@system[0].cronloglevel="9"
uci commit system
/etc/init.d/cron restart
ln -sf /sbin/ip /usr/bin/ip
ln -sf /usr/bin/wget /usr/bin/wget-ssl
#Flag packages
opkg flag hold luci-app-firewall
opkg flag hold firewall
opkg flag hold dnsmasq-full

rm -f /www/luci-static/resources/view/status/include/50_dsl.js
rm -f /www/luci-static/resources/view/status/include/70_ddns.js
rm -f /www/luci-static/resources/view/status/include/80_minidlna.js
rm -f /www/luci-static/resources/view/status/include/80_upnp.js
[ -f '/rom/etc/rpcd_10_system.js' ] && rm -f /etc/rpcd_10_system.js
[ -f '/rom/etc/rpcd_10_system.js' ] && rm -f /www/luci-static/resources/view/status/include/10_system.js
[ -f '/rom/etc/rpcd_10_system.js' ] && cp -f /rom/etc/rpcd_10_system.js /www/luci-static/resources/view/status/include/10_system.js
[ -f '/etc/fucked' ] && sed -i '/Source Code/d' /www/luci-static/resources/view/status/include/10_system.js
[ -f '/rom/etc/rpcd_10_system.js' ] && touch /etc/fucked
rm -rf /tmp/luci-modulecache
rm -f /tmp/luci-indexcache

exit 0
